"""add generated_day has_lifetime columns

Revision ID: a5f4ae11e106
Revises: 942972bc1fdf
Create Date: 2021-01-10 20:03:17.453040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f4ae11e106'
down_revision = '942972bc1fdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('generated_day', sa.Date(), nullable=False))
    op.add_column('link', sa.Column('hash_lifetime', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link', 'hash_lifetime')
    op.drop_column('link', 'generated_day')
    # ### end Alembic commands ###
